In [2]:
import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("GPUs:", tf.config.list_physical_devices('GPU'))

TensorFlow: 2.20.0
GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [3]:

x = tf.constant([[-2.0], [-1.0], [0.0], [1.0], [2.0]])

print("Input")
print(x)

print("ReLU")
print(tf.nn.relu(x))

print("Sigmoid")
print(tf.nn.sigmoid(x))

print("Tanh")
print(tf.nn.tanh(x))

I0000 00:00:1782325038.332655    1403 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5518 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4070 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9


Input
tf.Tensor(
[[-2.]
 [-1.]
 [ 0.]
 [ 1.]
 [ 2.]], shape=(5, 1), dtype=float32)
ReLU
tf.Tensor(
[[0.]
 [0.]
 [0.]
 [1.]
 [2.]], shape=(5, 1), dtype=float32)
Sigmoid
tf.Tensor(
[[0.11920292]
 [0.26894143]
 [0.5       ]
 [0.73105854]
 [0.880797  ]], shape=(5, 1), dtype=float32)
Tanh
tf.Tensor(
[[-0.9640276]
 [-0.7615942]
 [ 0.       ]
 [ 0.7615942]
 [ 0.9640276]], shape=(5, 1), dtype=float32)
